version: '3.8'

services:
  php-fpm:
    build: ./backend
    container_name: php_app
    volumes:
      - ./backend:/var/www/html
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - my_network

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  angular:
    build: ./frontend
    container_name: angular_app
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/app
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
